from rsf.proj import *

Flow('vp','vp.sgy', 
     ''' 
     segyread tape=$SOURCE | 
     put 
     n1=1282        d1=1.249       o1=0          label1="Depth" unit1="m" 
     n2=5605        d2=1.249       o2=0          label2="Distance" unit2="m"
     ''')
Flow('vs','vs.sgy', 
     ''' 
     segyread tape=$SOURCE | 
     put 
     n1=1282        d1=1.249       o1=0          label1="Depth" unit1="m" 
     n2=5605        d2=1.249       o2=0          label2="Distance" unit2="m"
     ''')
Flow('den','den.sgy', 
     ''' 
     segyread tape=$SOURCE | 
     put 
     n1=1282        d1=1.249       o1=0          label1="Depth" unit1="m" 
     n2=5605        d2=1.249       o2=0          label2="Distance" unit2="m"
     ''')

#     window n1=802
Plot('vp','vp','grey mean=y color=j')
Plot('vs','vs','grey mean=y color=j')
Plot('den','den','grey mean=y color=j')
Result('v','vp vs','SideBySideAniso')
End()

