/* This file is automatically generated. DO NOT EDIT! */

#ifndef _myfree_h
#define _myfree_h


void free1int(int *p);
/*< free1int >*/


void free2int(int **p);
/*< free2int >*/


void free1float(float *p);
/*< free1float >*/


void free2float(float **p);
/*< free2float >*/


void free1complex(sf_complex *p);
/*< free1complex >*/


void free2complex(sf_complex **p);
/*< free2complex >*/

#endif
