/* This file is automatically generated. DO NOT EDIT! */

#ifndef _ocpatch5d_h
#define _ocpatch5d_h


#ifndef _LARGEFILE_SOURCE
#define _LARGEFILE_SOURCE
#endif
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>


#include <rsf.h>


void ocpatch_init(int dim     /* number of dimensions */, 
		  int nw      /* total patch size */, 
		  int np1     /* total number of patches */, 
		  int* npatch /* number of patches [dim] */, 
		  int* nwall  /* data size [dim] */, 
		  int* nwind  /* patch size [dim] */);
/*< initialize >*/


void ocpatch_close(void);
/*< free allocated storage >*/


void ocpatch_lop (int ip      /* patch number */, 
		  bool adj    /* pull or push */, 
		  FILE *wall  /* data */, 
		  float* wind /* patch */);
/*< apply patching >*/


void ocpatch_flop (int ip       /* patch number */, 
		   bool adj     /* pull or push */, 
		   sf_file wall /* data */, 
		   float* wind  /* patch */);
/*< apply patching with RSF files >*/

#endif
