/* This file is automatically generated. DO NOT EDIT! */

#ifndef _perturb4d_h
#define _perturb4d_h


#include <rsf.h>


void perturb4d(sf_complex *d,int n1,int n2,int n3,int n4,float var1,float var2,float var3,float var4);
/*< perturb the position of data in a 4d array >*/

#endif
