from rsf.proj import *

Flow('reflect',None,'''
           spike n1=250 n2=500 d1=0.008 d2=10 
           nsp=1 
           mag=1 
           k1=75 
           k2=250
           l1=75 
           l2=250
           p1=0 
           p2=0 |
           put title="Reflectivity Model" label2="Position" unit2="m" n3=1 d3=1 o3=0 | 
           spray axis=3 n=25 d=100 o=100 label="Offset" unit="m" |
           ricker1 frequency=10
           ''')

Flow('vp',None,
     '''
     makevel n1=250 n2=500 v000=2500 dvdx1=1.5 dvdx2=0 
     ''') 

Flow('vs',None,
     '''
     makevel n1=250 n2=500 v000=1500 dvdx1=1.2 dvdx2=0 
     ''') 

Plot('vp',
       '''
       grey allpos=y mean=y scalebar=y
       ''')

Plot('vs',
       '''
       grey allpos=y mean=y scalebar=y
       ''')

Flow('d','reflect',
     '''
     pstm
     adj=n
     vp=vp.rsf
     vs=vs.rsf
     aperture=4000
     ps=y
     verbose=y
     ''')

Result('d',
       '''
       window n3=1 f3=10 j2=4 f2=5 | 
       grey minval=-0.01 maxval=0.01 clip=0.01 color=I scalebar=y
       ''')


Flow('reflect_adj','d',
     '''
     pstm
     adj=y
     vp=vp.rsf
     vs=vs.rsf
     aperture=4000
     ps=y
     verbose=y
     ''')

#Flow('reflect_inv misfit','d',
#     '''
#     pstm
#     inv=y
#     itmax_internal=20
#     itmax_external=1
#     misfit=${TARGETS[1]}
#     vp=vp.rsf
#     vs=vs.rsf
#     aperture=4000
#     ps=y
#     verbose=y
#     ''')

# Dot product test 
#Flow('dot.test','d reflect',
#     '''
#     dottest sfpstm
#     dat=${SOURCES[0]} 
#     mod=${SOURCES[1]}
#     vp=vp.rsf
#     vs=vs.rsf
#     aperture=4000
#     ps=y
#     verbose=n
#     ''',stdin=0,stdout=-1)

Plot('reflect',
       '''
       window n3=1 f3=10 j2=4 f2=5 | 
       grey minval=-0.01 maxval=0.01 clip=0.01 color=i scalebar=y label2="x" unit2="m" title="(a)"
       ''')

Plot('d',
       '''
       window n3=1 f3=10 | 
       grey minval=-0.001 maxval=0.001 clip=0.001 color=i scalebar=y label2="x" unit2="m" title="(b)"
       ''')

Plot('reflect_adj',
       '''
       window n3=1 f3=10 j2=4 f2=5 | 
       grey minval=-0.01 maxval=0.01 clip=0.01 color=i scalebar=y label2="x" unit2="m" title="(c)"
       ''')

#Plot('reflect_inv',
#       '''
#       window n3=1 f3=10 j2=4 f2=5 | 
#       grey minval=-0.05 maxval=0.05 clip=0.05 color=i scalebar=y label2="x" unit2="m" title=" "
#       ''')

Result('impulse','reflect d reflect_adj','SideBySideIso')

#Result('misfit',
#       '''
#       graph
#       ''')

End()

