import os

os.environ['OMP_NUM_THREADS'] = '6'

from rsf.proj import *

#read segy
Flow('d_raw headers','/u3/data/xom/kearl/kearl_2dline.su',
     '''
     segyread su=y suxdr=y tape=${SOURCES[0]} tfile=${TARGETS[1]}
     ''',stdin=0)

Flow('d0_raw','d_raw',
     '''
     window f2=0 j2=3
     ''')

Flow('d1_raw','d_raw',
     '''
     window f2=1 j2=3
     ''')

Flow('d2_raw','d_raw',
     '''
     window f2=2 j2=3
     ''')

Flow('headers0','headers',
     '''
     window f2=0 j2=3
     ''')

Flow('headers0_binned','headers0',
     '''
     geom5d mode=1 
     osx=491389  dsx=4 
     osy=6360834 dsy=4 
     ogx=491387  dgx=2
     ogy=6360833 dgy=2 
     gamma=1 ang=90 
     headin=${SOURCES[0]} headout=${TARGETS[0]}
     ''',stdin=0,stdout=-1)

Flow('d0_raw_binned headers0_binned2','d0_raw headers0_binned',
     '''
     pad5d mode=1 
     min_ix1=0 max_ix1=0 
     min_ix2=0 max_ix2=249 
     min_ix3=0 max_ix3=0 
     min_ix4=0 max_ix4=500 
     headin=${SOURCES[1]} headout=${TARGETS[1]}
     ''')

Flow('d1_raw_binned headers1_binned2','d1_raw headers0_binned',
     '''
     pad5d mode=1 
     min_ix1=0 max_ix1=0 
     min_ix2=0 max_ix2=249 
     min_ix3=0 max_ix3=0 
     min_ix4=0 max_ix4=500 
     headin=${SOURCES[1]} headout=${TARGETS[1]}
     ''')

Flow('d2_raw_binned headers2_binned2','d2_raw headers0_binned',
     '''
     pad5d mode=1 
     min_ix1=0 max_ix1=0 
     min_ix2=0 max_ix2=249 
     min_ix3=0 max_ix3=0 
     min_ix4=0 max_ix4=500 
     headin=${SOURCES[1]} headout=${TARGETS[1]}
     ''')

Flow('r_',None,'math n1=501 d1=2 o1=3 output=0')
Flow('gx','r_','math output="x1"')

shots_x = []
shots_z = []
offsets = []
nsx = 250
dsx = 4.0
osx = 4.0
for ishot in range(0,nsx):
     sx = osx + ishot*dsx
     shot_x = 'd1_shot_%d' % ishot
     shots_x.append(shot_x)
     shot_z = 'd0_shot_%d' % ishot
     shots_z.append(shot_z)
     Flow('d0_raw_shot_%d' % ishot,'d0_raw_binned',
          '''
          window n3=1 f3=%d 
          ''' % ishot)
     Flow('d1_raw_shot_%d' % ishot,'d1_raw_binned',
          '''
          window n3=1 f3=%d 
          ''' % ishot)
     Flow('d2_raw_shot_%d' % ishot,'d2_raw_binned',
          '''
          window n3=1 f3=%d 
          ''' % ishot)
     Flow('mask0_%d' % ishot,'d0_raw_shot_%d' % ishot,'math output="abs(input)" | stack axis=1 | mask min=0 max=1e4')
     Flow('offset_%d' % ishot,'gx','math output="input-%g"' % sx)
     offset = 'offset_%d' % ishot
     offsets.append(offset)
     Flow('d0_shot_%d' % ishot,'d0_raw_shot_%d mask0_%d' % (ishot,ishot),
          '''
          headercut mask=${SOURCES[1]} |
          fkfilter pa=-0.002 pb=-0.001 pc=0.001 pd=0.002 |
          headercut mask=${SOURCES[1]} |
          shift del1=0.02 |
          bandpass flo=3 fhi=400 |
          headercut mask=${SOURCES[1]}
          ''')
     Flow('d1_shot_%d' % ishot,'d1_raw_shot_%d mask0_%d' % (ishot,ishot),
          '''
          headercut mask=${SOURCES[1]} |
          fkfilter pa=-0.002 pb=-0.001 pc=0.001 pd=0.002 |
          headercut mask=${SOURCES[1]} |
          shift del1=0.02 |
          bandpass flo=3 fhi=400 |
          headercut mask=${SOURCES[1]}
          ''')
     Flow('d2_shot_%d' % ishot,'d2_raw_shot_%d mask0_%d' % (ishot,ishot),
          '''
          headercut mask=${SOURCES[1]} |
          fkfilter pa=-0.002 pb=-0.001 pc=0.001 pd=0.002 |
          headercut mask=${SOURCES[1]} |
          shift del1=0.02 |
          bandpass flo=3 fhi=400 |
          headercut mask=${SOURCES[1]}
          ''')

Flow('h',offsets,
     '''
     cat axis=2 ${SOURCES[1:%d]}
     ''' % nsx)

Flow('ux_shots',shots_x,
     '''
     cat axis=3 ${SOURCES[1:%d]} |
     put o3=%d d3=%d label3="sx" unit3=m label2="gx" unit2=m |
     put label2="Gx" unit2="m" label3="Sx" unit3="m" o2=3 d2=2 o3=4 d3=4
     ''' % (nsx,osx,dsx))

Flow('uz_shots',shots_z,
     '''
     cat axis=3 ${SOURCES[1:%d]} |
     put o3=%d d3=%d label3="sx" unit3=m label2="gx" unit2=m |
     put label2="Gx" unit2="m" label3="Sx" unit3="m" o2=3 d2=2 o3=4 d3=4
     ''' % (nsx,osx,dsx))

Flow('ux_shots1','ux_shots h',
     '''
     mutter offset=${SOURCES[1]} half=n t0=0.025 v0=1800 abs=y inner=n
     ''')

Flow('uz_shots1','uz_shots h',
     '''
     mutter offset=${SOURCES[1]} half=n t0=0.025 v0=1800 abs=y inner=n
     ''')

Flow('ux_cmps','ux_shots',
     '''
     gxsxtomxhx 
     omx=3 dmx=2 nmx=500
     ohx=-500 dhx=4 nhx=251
     verbose=n |
     transp plane=23
     ''')

Flow('uz_cmps','uz_shots',
     '''
     gxsxtomxhx 
     omx=3 dmx=2 nmx=500
     ohx=-500 dhx=4 nhx=251
     verbose=n |
     transp plane=23
     ''')

# 
# make velocity model
Flow('vmask',None,
    '''
     spike nsp=1 
     n1=500 n2=501 d1=0.5 d2=2 k1=1 k2=1 l1=1 l2=501 mag=1 p2=0 |
     put o1=0 o2=0 label1="z" label2="x" unit1="m" unit2="m" 
     ''',stdin=-1)

Flow('vp','p_sonic.txt vmask',
     '''
     csv2rsf | 
     transp plane=12 |
     put o1=0 d1=5 label1="Depth" unit1="m" |
     sinc o1=0 n1=500 d1=0.5 | 
     spray axis=2 n=501 d=2 o=0 label="x" unit="m" |
     smooth rect1=25 |
     math mask=${SOURCES[1]} output="input - input*mask + 380*mask" |
     math output="input*1.2"
     ''')
Flow('vs','vp',
     '''
     math output="input*0.5774"
     ''')
# Wavelet
Flow('wav',None,
     '''
     spike mag=1 n1=1000 d1=0.0005 k1=40 | 
     ricker1 frequency=300 
     ''')

Flow('mpp mps','ux_shots1 uz_shots1 vp vs wav',
     '''
     mpiewem_poynting adj=y H=y calc_ang=y
     ux=${SOURCES[0]} uz=${SOURCES[1]} vp=${SOURCES[2]} vs=${SOURCES[3]} wav=${SOURCES[4]} 
     mpp=${TARGETS[0]} mps=${TARGETS[1]}
     verbose=y
     nz=500 oz=0 dz=0.5
     npx=37 dpx=5 opx=-90
     fmin=3 fmax=400
     sz=1.5 gz=0
     ''',np=5,stdin=0,stdout=-1)

Flow('mpp2 mps2','ux_shots1 uz_shots1 vp vs wav',
     '''
     mpivwem adj=y
     ux=${SOURCES[0]} uz=${SOURCES[1]} vp=${SOURCES[2]} vs=${SOURCES[3]} wav=${SOURCES[4]} 
     mpp=${TARGETS[0]} mps=${TARGETS[1]}
     verbose=y
     nz=500 oz=0 dz=0.5
     npx=37 dpx=5 opx=-90
     fmin=3 fmax=400
     sz=1.5 gz=0
     ''',np=5,stdin=0,stdout=-1)

Plot('ux','ux_shots','window n3=1 f3=125 | grey color=e title="Shot Gather" titlesz=20')
Plot('uz','uz_shots','window n3=1 f3=125 | grey color=e title="Shot Gather" titlesz=20')
Plot('mpp_gather','mpp','window n2=1 f2=250 | grey minval=-100 maxval=100 clip=100 color=e title="MPP Gather" titlesz=20')
Plot('mps_gather','mps','window n2=1 f2=250 | grey minval=-100 maxval=100 clip=100 color=e title="MPS Gather" titlesz=20')
Plot('mpp_stack','mpp','window min3=-30 max3=30 | stack axis=3 | grey minval=-10 maxval=10 clip=10 color=e title="MPP Stack" titlesz=20')
Plot('mps_stack','mps','window min3=-30 max3=30 | stack axis=3 | grey minval=-10 maxval=10 clip=10 color=e title="MPS Stack" titlesz=20')
Result('d','ux uz','SideBySideAniso')
Result('m','mpp_gather mps_gather mpp_stack mps_stack','SideBySideAniso')

Plot('mpp2_gather','mpp2','window n2=1 f2=250 | grey minval=-100 maxval=100 clip=100 color=e title="MPP Gather" titlesz=20')
Plot('mps2_gather','mps2','window n2=1 f2=250 | grey minval=-100 maxval=100 clip=100 color=e title="MPS Gather" titlesz=20')
Plot('mpp2_stack','mpp2','window min3=-30 max3=30 | stack axis=3 | grey minval=-10 maxval=10 clip=10 color=e title="MPP Stack" titlesz=20')
Plot('mps2_stack','mps2','window min3=-30 max3=30 | stack axis=3 | grey minval=-10 maxval=10 clip=10 color=e title="MPS Stack" titlesz=20')
Result('m2','mpp2_gather mps2_gather mpp2_stack mps2_stack','SideBySideAniso')


End()


