import os

os.environ['OMP_NUM_THREADS'] = '8'

from rsf.proj import *

# make velocity model
Flow('vp',None,
     '''
     spike nsp=4 n1=600 n2=700 d1=5 d2=10 k1=1,201,201,201 k2=1,1,1,1 l1=600,600,600,600 l2=700,700,700,700 mag=2200,200,200,200 p2=0,0,0.4,0.8 |
     put o1=0 o2=10 label1="z" label2="x" unit1="m" unit2="m"
     ''',stdin=-1)
#Flow('vp',None,
#     '''
#     spike nsp=2 n1=600 n2=700 d1=5 d2=10 k1=1,201 k2=1,1 l1=600,600 l2=700,700 mag=2200,200 p2=0,0 |
#     put o1=0 o2=10 label1="z" label2="x" unit1="m" unit2="m"
#     ''',stdin=-1)

# Density
Flow('den','vp','math output=1')

# Explicit about c13 c33
Flow('c11','vp den','math vp=${SOURCES[0]} den=${SOURCES[1]} output="den*vp^2" | smooth rect1=4 rect2=4 repeat=3')
Flow('vs','vp','math vp=${SOURCES[0]} output="vp/sqrt(3)" ')
Flow('c55','vs den','math vs=${SOURCES[0]} den=${SOURCES[1]} output="den*vs^2" | smooth rect1=4 rect2=4 repeat=3')
Flow('c33','c11','cp')
Flow('c13','c11 c55','math c11=${SOURCES[0]} c55=${SOURCES[1]} output="c11-2*c55" ')
Flow('ccc','c11 c33 c55 c13','cat axis=3 ${SOURCES[1:4]} ')

Plot('vp','vp','grey mean=y scalebar=y')
Plot('vs','vs','grey mean=y scalebar=y')
Result('v','vp vs','OverUnderAniso')
 
End()
