from rsf.proj import *

# get velocity model
Fetch('vel.bin',
      server='http://ualberta.ca',
      top='~kstanton',
      dir='files')
Flow('vel','vel.bin',
     '''
     bin2rsf d1=5 d2=10 n1=600 n2=700 bfile=${SOURCES[0]} |
     put o1=0 o2=10 label1="z" label2="x" unit1="m" unit2="m"
     ''',stdin=-1)

# Density
Flow('den','vel','math output=1')
 
Flow('r_',None,'math n1=700 d1=10 o1=10 output=0')
Flow('s_',None,'math n1=1   d1=0  o1=0  output=0')
# receiver positions
Flow('zr','r_','math output=10')
Flow('xr','r_','math output="x1"')
Flow('rec',['xr','zr'],'''cat axis=2 space=n
     ${SOURCES[0]} ${SOURCES[1]} | transp
     ''', stdin=0)

# Wavelet
Flow('wav',None,
     '''
     spike mag=0.1 n1=4000 d1=0.001 k1=200 | 
     ricker1 frequency=20 
     ''')

shots = []
nsx = 50
dsx = 100.0
osx = 1000.0
for ishot in range(0,nsx):
     sx = osx + ishot*dsx
     shot = 'd_%d' % ishot
     shots.append(shot)
     # shot positions
     Flow('zs_%d' % ishot,'s_','math output=10')
     Flow('xs_%d' % ishot,'s_','math output=%d' % sx)
     Flow('rs_%d' % ishot,'s_','math output=1')
     Flow('src_%d' % ishot,['xs_%d' % ishot,'zs_%d' % ishot,'rs_%d' % ishot],'''
          cat axis=2 space=n
          ${SOURCES[0]} ${SOURCES[1]} ${SOURCES[2]} | transp
          ''', stdin=0)
     # offset
     Flow('offset_%d' % ishot,'xr','math output="input-%g"' % sx)
     # Finite-difference modeling
     Flow('d_fd_%d' % ishot,'wav vel den src_%d rec' % ishot,
          '''
          transp | 
          awefd2d 
          vel=${SOURCES[1]} den=${SOURCES[2]} 
          sou=${SOURCES[3]} rec=${SOURCES[4]} wfl=${TARGETS[1]} 
          verb=y free=n snap=n dabc=y jdata=1 nb=250 ompnth=8
          ''')
     Flow('d_%d' % ishot,'d_fd_%d offset_%d' % (ishot,ishot),
          '''
          transp |
          mutter offset=${SOURCES[1]} v0=1500 t0=0.25 half=n
          ''')

Flow('d_gxsx',shots,
     '''
     cat axis=3 ${SOURCES[1:%d]} |
     put o3=%d d3=%d label3="sx" unit3=m label2="gx" unit2=m |
     math output=input*10e5 |
     window j1=4 |
     bandpass fmax=125
     ''' % (nsx,osx,dsx))

# remove the source delay from the receiver data
Flow('d','d_gxsx',
     '''
     gxsxtomxhx nmx=700 omx=10 dmx=10 nhx=201 ohx=-2000 dhx=20 verbose=n | 
     window n3=1 f3=100 |
     window n1=950 f1=50 |
     put o1=0
     ''')

Flow('wav_resample','wav',
     '''
     window j1=4
     ''')

Flow('m','d vel wav_resample',
     '''
     sfzowem adj=y op=4
     fmin=0 fmax=50
     nz=600 oz=0 dz=5     
     verbose=y
     vp=${SOURCES[1]}
     numthreads=8
     ''')

Result('d_gxsx','d_gxsx','window n3=1 f3=24 | grey pclip=98 scalebar=y')
Result('d','d','grey pclip=98 scalebar=y')
Result('m','m','grey pclip=98 scalebar=y')

End()

