import os

os.environ['OMP_NUM_THREADS'] = '8'

from rsf.proj import *

Flow('mpp mps','../ux.rsf ../uz.rsf ../vp_smooth.rsf ../vs_smooth.rsf ../wav_resample.rsf',
     '''
     mpiewem_poynting adj=y H=y
     ux=${SOURCES[0]} uz=${SOURCES[1]} vp=${SOURCES[2]} vs=${SOURCES[3]} wav=${SOURCES[4]} 
     mpp=${TARGETS[0]} mps=${TARGETS[1]}
     verbose=y
     nz=600 oz=0 dz=5 
     npx=1 dpx=5 opx=0
     gz=10 sz=10
     fmin=3 fmax=50
     sz=10 gz=10
     ''',np=4,stdin=0,stdout=-1)

Flow('ux_fwd uz_fwd','mpp mps ../vp_smooth.rsf ../vs_smooth.rsf ../wav_resample.rsf',
     '''
     mpiewem adj=n
     mpp=${SOURCES[0]} mps=${SOURCES[1]} vp=${SOURCES[2]} vs=${SOURCES[3]} wav=${SOURCES[4]} 
     ux=${TARGETS[0]} uz=${TARGETS[1]}
     verbose=y
     nz=600 oz=0 dz=5 
     nhx=1 dhx=5 ohx=0 
     npx=1 dpx=5 opx=0
     nt=1000 dt=0.004 ot=0
     nsx=50 dsx=100 osx=1000
     gz=10 sz=10
     fmin=3 fmax=50
     sz=10 gz=10
     ''',np=4,stdin=0,stdout=-1)

plotpard = 'color=seismic label1=t label2=x title=""'
Plot('ux','../ux.rsf','window min3=3500 max3=3500 | grey %s' %plotpard)
Plot('uz','../uz.rsf','window min3=3500 max3=3500 | grey %s' %plotpard)
Result('d','ux uz','SideBySideAniso')
Plot('ux_fwd','window min3=3500 max3=3500 | grey %s'%plotpard)
Plot('uz_fwd','window min3=3500 max3=3500 | grey %s' %plotpard)
Result('d_fwd','ux_fwd uz_fwd','SideBySideAniso')

End()
