from rsf.proj import *
 
# make data with linear events
Flow('dtrue',None,
     '''
     linearevents5d
     n1=500 n2=250 n3=1 n4=1 n5=1 
     d1=0.004 d2=50 
     nevent=2 amp=1,-1 t0=0.3,1.0 f0=20,30 v1=1200,-1500 
     title="true data" 
     ''',stdin=0) 

# decimate traces
Flow('ddec','dtrue','decimate mode=2 inc2=2') 
Flow('ddec3','dtrue','decimate mode=2 inc2=3') 
Flow('ddec4','dtrue','decimate mode=2 inc2=4') 
Flow('ddec5','dtrue','decimate mode=2 inc2=5') 

# POCS interpolation
Flow('dpocs','ddec','reg5d method=1 iter=100 alphai=1 alphaf=1 verbose=0 fmax=100') 

Flow('dpocs2','ddec','pocs5d niter=2000 fmax=100 p=100 aa2=20') 

plotpar1='color=i label1="T" unit1="s" label2="X" unit2="m" title="" labelsz=10'
Plot('dtrue','grey %s' %plotpar1)
Plot('ddec','grey %s' %plotpar1)
Plot('ddec3','grey %s' %plotpar1)
Plot('ddec4','grey %s' %plotpar1)
Plot('ddec5','grey %s' %plotpar1)
Plot('dpocs','grey %s' %plotpar1)
Plot('dpocs2','grey %s' %plotpar1)
plotpar2='color=j allpos=y pclip=99.9 label1="Frequency" unit1="1/s" label2="Wavenumber" unit2="1/m" title="" labelsz=10'
Plot('dtrue_fk','dtrue','fft1 | fft3 | cabs | grey %s' %plotpar2)
Plot('ddec_fk','ddec','fft1 | fft3 | cabs | grey %s' %plotpar2)
Plot('ddec3_fk','ddec3','fft1 | fft3 | cabs | grey %s' %plotpar2)
Plot('ddec4_fk','ddec4','fft1 | fft3 | cabs | grey %s' %plotpar2)
Plot('ddec5_fk','ddec5','fft1 | fft3 | cabs | grey %s' %plotpar2)
Plot('dpocs_fk','dpocs','fft1 | fft3 | cabs | grey %s' %plotpar2)
Plot('dpocs2_fk','dpocs2','fft1 | fft3 | cabs | grey %s' %plotpar2)
Result('true','dtrue dtrue_fk','SideBySideAniso')
Result('dec','ddec ddec_fk','SideBySideAniso')
Result('pocs','dpocs dpocs_fk','SideBySideAniso')
Result('pocs2','dpocs2 dpocs2_fk','SideBySideAniso')


Result('dec3','ddec3 ddec3_fk','SideBySideAniso')
Result('dec4','ddec4 ddec4_fk','SideBySideAniso')
Result('dec5','ddec5 ddec5_fk','SideBySideAniso')

End()
