import os
os.environ['OMP_NUM_THREADS'] = '8'
from rsf.proj import *

Flow('vrms','/u1/data/GOM_data/vrms.txt',
     '''
     echo n1=334 o1=0 d1=0.03 n2=10 o2=1002 d2=200 data_format=ascii_float in=${SOURCES[0]} |
     sfdd form=native |
     window n2=4 f2=4 |
     put o2=847070 d2=8810
     ''')
Flow('vint','vrms',
     '''
     math output="input*0.3048" |
     dix niter=100 rect1=5 rect2=0 
     ''')
Flow('v','vint',
     '''
     time2depth  velocity=${SOURCES[0]} intime=y nz=600 dz=10 |
     put label1=Depth unit1=m |
     transp |
     sinc o1=847070 n1=992 d1=26.67 |
     transp |
     window min2=847070 max2=873499.97 |
     put o2=8471
     ''')

Flow('d_raw headers','d.su',
     '''
     segyread su=y suxdr=y tape=${SOURCES[0]} tfile=${TARGETS[1]}
     ''',stdin=0)


# Wavelet
Flow('wav',None,
     '''
     spike mag=0.1 n1=1251 d1=0.004 k1=1 l1=1
     ''')

#Flow('wav headers_w','w.su',
#     '''
#     segyread su=y suxdr=y tape=${SOURCES[0]} tfile=${TARGETS[1]} |
#     pad end1=1219
#     ''',stdin=0)


Flow('headers_float','headers','dd type=float')
Flow('sx','headers_float','window n1=1 f1=21')
Flow('sy','headers_float','window n1=1 f1=22')
Flow('shots','sx sy','cmplx ${SOURCES[0]} ${SOURCES[1]}',stdin=0)
Flow('gx','headers_float','window n1=1 f1=23')
Flow('gy','headers_float','window n1=1 f1=24')
Flow('receivers','gx gy','cmplx ${SOURCES[0]} ${SOURCES[1]}',stdin=0)
Plot('shots','graph min2=-20 max2=20 symbol="."')
Plot('receivers','graph min2=-20 max2=20 symbol="."')

Flow('headers_binned','headers',
     '''
     geom5d mode=1 
            osx=4378375 dsx=8750
            osy=0 dsy=10
            ogx=2779100 dgx=8750
            ogy=0 dgy=10
            gamma=1 ang=90 headin=${SOURCES[0]} headout=${TARGETS[0]}
     ''',stdin=0,stdout=-1)

Flow('d_binned headers_binned2','d_raw headers_binned',
     '''
     pad5d
     headin=${SOURCES[1]}         
     headout=${TARGETS[1]}        
     max_ix1=809
     max_ix2=0
     max_ix3=991
     max_ix4=0
     min_ix1=0
     min_ix2=0
     min_ix3=0
     min_ix4=0
     mode=1 |
     put label2="Sx" label3="Sy" label4="Gx" label5="Gy" unit2="" unit3="" unit4="" unit5=""
     ''')
Flow('d','d_binned','window n3=1 | transp memsize=10000 plane=23 | put d2=26.67 o2=8471 d3=26.67 o3=13345 unit2="m" unit3="m" | window max1=5')

# decimate traces by masking and random decimation
Flow('mask',None,'spike mag=1 nsp=1 k1=0 k2=0 l1=1 l2=992 p1=0 p2=0 n1=1 n2=992 o1=0 o2=8471 d1=0.004 d2=26.67 | noise type=n rep=y | mask min=0 max=0.5 | sfdd type=float | sfspray axis=1 n=1251 | spray axis=3 n=810 | transp plane=24 memsize=10000 | put o3=13345 d4=1 d5=1 o4=0 o5=0',stdin=0) 

Flow('ddec','d mask',
     '''
     math x=${SOURCES[0]} y=${SOURCES[1]} output="(1-y)*x"
     ''') 

#Flow('d_1shot','d','window n3=1 f3=500 min2=20000 max2=28000')
#Flow('ddec_1shot','ddec','window n3=1 f3=500 min2=20000 max2=28000')

#Flow('d_1shot2','d_1shot',
#     '''
#     spike mag=1 nsp=1 k1=0 l1=1251 p1=0 n1=1251 o1=0 d1=0.004 k2=1 l2=125 p2=0 n2=301 o2=19992.4 d2=26.67 |
#     math x=${SOURCES[0]} output="input*x" |
#     put n3=1 d3=26.67 o3=26680 
#     ''',stdin=0)
#
#Flow('d_1shot3','d_1shot',
#     '''
#     spike mag=1 nsp=1 k1=0 l1=1251 p1=0 n1=1251 o1=0 d1=0.004 k2=151 l2=301 p2=0 n2=301 o2=19992.4 d2=26.67 |
#     math x=${SOURCES[0]} output="input*x" |
#     put n3=1 d3=26.67 o3=26680 
#     ''',stdin=0)


Flow('v_1shot','v',
     ''' 
     transp |
     sinc o1=19992.4 n1=1806 d1=4.445 |
     transp |
     math output="2000"
     ''')

Flow('d_1shot','d',
     '''
     window n3=1 f3=500 min2=20000 max2=28000 |
     lpad jump=3
     ''')

Flow('mask_1shot','d_1shot',
     '''
     spike mag=1 nsp=1 k1=1 l1=1251 p1=0 n1=1251 o1=0 d1=0.004 k2=205 l2=748 p2=0 n2=903 o2=19992.4 d2=8.89 |
     put n3=1 d3=26.67 o3=26680
     ''',stdin=0)

Flow('d_1shot2',None,
     '''
     linearevents5d amp=1,0 f0=20,20 t0=5,6 v1=-1500,-4000 v2=9999,9999 v3=9999,9999 v4=9999,9999 
     
                    nevent=2 n1=1251 n2=903 n3=1 n4=1 n5=1 
                    o1=0 o2=19992.4 o3=26680 o4=0 o5=0 
                    d1=0.004 d2=8.89 d3=26.67 d4=1 d5=1
     ''',stdin=0)               

Flow('m','d_1shot v_1shot wav',
     '''
     mpiwem_poynting adj=y aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=600 oz=0 dz=10
     npx=1 dpx=1 opx=0
     gz=10 sz=10
     fmin=1 fmax=70
     ''',np=1,stdin=0,stdout=-1)

Flow('d_1shot_fwd','m v_1shot wav',
     '''
     mpiwem_poynting adj=n aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=600 oz=0 dz=10
     npx=1 dpx=1 opx=0
     nt=1251 dt=0.004 ot=0 
     nsx=1 dsx=26.67 osx=26680
     gz=10 sz=10
     fmin=1 fmax=70
     ''',np=1,stdin=0,stdout=-1)

Flow('m_inv misfit','d_1shot v_1shot wav',
     '''
     lswem_poynting niter=50 
     d=${SOURCES[0]} m=${TARGETS[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} misfit=${TARGETS[1]}
     np=1 npersocket=1 reg=n
     verbose=y
     nz=600 oz=0 dz=10
     npx=1 dpx=1 opx=0
     nt=1251 dt=0.004 ot=0 
     nsx=1 dsx=26.67 osx=26680
     gz=10 sz=10
     fmin=1 fmax=70
     ''',stdin=0,stdout=-1)

Flow('d_1shot_fwd1','m_inv v_1shot wav',
     '''
     mpiwem_poynting adj=n aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=600 oz=0 dz=10
     npx=1 dpx=1 opx=0
     nt=1251 dt=0.004 ot=0 
     nsx=1 dsx=26.67 osx=26680
     gz=10 sz=10
     fmin=1 fmax=70
     ''',np=1,stdin=0,stdout=-1)

plotpar1='color=i title="" label1="T" unit1="s" label2="X" unit2="m"'
Plot('din','d_1shot','window min2=21800 max2=26700 | grey %s' %plotpar1)
Plot('dout','d_1shot_fwd mask_1shot','math x=${SOURCES[0]} y=${SOURCES[1]} output="x*y" | window min2=21800 max2=26700 | grey %s' %plotpar1,stdin=0)
Plot('dout1','d_1shot_fwd1 mask_1shot','math x=${SOURCES[0]} y=${SOURCES[1]} output="x*y" | window min2=21800 max2=26700 | grey %s' %plotpar1,stdin=0)
Result('m','m','grey title="" labelsz=10 label1="Z" unit1="m" label2="X" unit2="m"')
Result('m_inv','m_inv','grey title="" labelsz=10 label1="Z" unit1="m" label2="X" unit2="m"')

plotpar2='color=j title="" label1="Frequency" unit1="1/m" label2="Wavenumber" unit2="1/m" allpos=y'
Plot('din_fk','d_1shot','window min2=21800 max2=26700 | fft1 | fft3 | cabs | window max1=70 | grey %s'%plotpar2)
Plot('dout_fk','d_1shot_fwd mask_1shot','math x=${SOURCES[0]} y=${SOURCES[1]} output="x*y" | window min2=21800 max2=26700 | fft1 | fft3 | cabs | window max1=70 | grey %s' %plotpar2,stdin=0)
Plot('dout1_fk','d_1shot_fwd1 mask_1shot','math x=${SOURCES[0]} y=${SOURCES[1]} output="x*y" | window min2=21800 max2=26700 | fft1 | fft3 | cabs | window max1=70 | grey %s' %plotpar2,stdin=0)

Result('input','din din_fk','SideBySideAniso')
Result('adj','dout dout_fk','SideBySideAniso')
Result('inv','dout1 dout1_fk','SideBySideAniso')

Result('misfit','graph title="" labelsz=10')

End()
