from rsf.proj import *
import math
 
# plotting
plotpar='title="" color=i minval=-4e4 maxval=4e4 clip=4e4'

Plot('din_ts','../geotrace_land/din.rsf','window min1=2.35 max1=2.35 | grey %s' % plotpar)
Plot('din_xl','../geotrace_land/din.rsf','window min1=2.1 max1=2.6 min2=1000 max2=1000 max3=1200 | grey %s' % plotpar)
Plot('din_il','../geotrace_land/din.rsf','window min1=2.1 max1=2.6 min3=1000 max3=1000 max2=1200 | grey %s' % plotpar)

Plot('dpocs_ts','../geotrace_land/dpocs.rsf','window min1=2.35 max1=2.35 | grey %s' % plotpar)
Plot('dpocs_xl','../geotrace_land/dpocs.rsf','window min1=2.1 max1=2.6 min2=1000 max2=1000 max3=1200 | grey %s' % plotpar)
Plot('dpocs_il','../geotrace_land/dpocs.rsf','window min1=2.1 max1=2.6 min3=1000 max3=1000 max2=1200 | grey %s' % plotpar)

Plot('dpocs2_ts','../geotrace_land/dpocs2.rsf','window min1=2.35 max1=2.35 | grey %s' % plotpar)
Plot('dpocs2_xl','../geotrace_land/dpocs2.rsf','window min1=2.1 max1=2.6 min2=1000 max2=1000 max3=1200 | grey %s' % plotpar)
Plot('dpocs2_il','../geotrace_land/dpocs2.rsf','window min1=2.1 max1=2.6 min3=1000 max3=1000 max2=1200 | grey %s' % plotpar)

Result('ts','din_ts dpocs_ts dpocs2_ts','OverUnderIso')
Result('il','din_il dpocs_il dpocs2_il','SideBySideAniso')
Result('xl','din_xl dpocs_xl dpocs2_xl','SideBySideAniso')
End()
