import os

os.environ['OMP_NUM_THREADS'] = '6'

from rsf.proj import *

#read segy
Flow('d_raw headers_raw','/u3/data/arcis/woc/segy/processed_gathers_ils01.segy',
     '''
     segyread tape=${SOURCES[0]} tfile=${TARGETS[1]}
     ''',stdin=0)

End()
