import os
os.environ['OMP_NUM_THREADS'] = '8'
from rsf.proj import *

Flow('m',None,
     '''
     sigmoid n1=500 n2=500 large=2500 d1=0.004 d2=10 |
     put n3=1 d3=10 o3=0 |
     ricker1 frequency=50
     ''')
Flow('vp',None,'makevel n1=500 n2=500 v000=1500 dvdx1=1.5 dvdx2=0',stdin=0) 

Flow('d','m vp','pstm adj=n vp=${SOURCES[1]} ps=n aperture=500 verbose=y')
Flow('m_adj','d vp','pstm adj=y vp=${SOURCES[1]} ps=n aperture=500 verbose=y')

plotpar1='color=i title="" label1="T" unit1="s" label2="X" unit2="m"'
plotpar2='color=j allpos=y mean=y title="" label1="T" unit1="s" label2="X" unit2="m"'
#Result('vp','grey %s' %plotpar2)
#Result('m','grey %s' %plotpar1)
Result('d','grey %s' %plotpar1)
Result('m_adj','grey %s' %plotpar1)

End()

