import os
os.environ['OMP_NUM_THREADS'] = '8'
from rsf.proj import *

# velocity
Flow('vel','vel_raw',
     '''
     put label1=Z unit1=m label2=X unit2=m title="" unit="m/s"
     ''')

# Wavelet
Flow('wav',None,
     '''
     spike mag=0.1 n1=1000 d1=0.004 k1=1 l1=1 |
     ricker1 frequency=10
     ''')

# Reflectors
Flow('m',None,
     '''
     spike nsp=60
           mag=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
           k1=20,40,60,80,100,120,140,160,180,200,220,240,260,280,300,320,340,360,380,400,420,440,460,480,500,520,540,560,580,600,620,640,660,680,700,720,740,760,780,800,820,840,860,880,900,920,940,960,980,1000,1020,1040,1060,1080,1100,1120,1140,1160,1180,1200
           l1=20,40,60,80,100,120,140,160,180,200,220,240,260,280,300,320,340,360,380,400,420,440,460,480,500,520,540,560,580,600,620,640,660,680,700,720,740,760,780,800,820,840,860,880,900,920,940,960,980,1000,1020,1040,1060,1080,1100,1120,1140,1160,1180,1200
           k2=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
           l2=2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133,2133
           n1=1201 d1=7.62 n2=2133 d2=11.43 |
     ricker1 frequency=0.005 |
     put n3=1 d3=1 o3=0 o2=3055.62 
     ''',stdin=0)

Flow('wd',None,
     '''
     spike n1=2133 d1=11.43 o1=3055.62 |
     noise range=1 rep=y type=n |
     mask min=0 max=0.5 |
     dd type=float |
     spray axis=2 n=1000 |
     put d2=0.004 o2=0 |
     transp plane=12
     ''',stdin=0)

Flow('d_fwd_5000','m vel wav',
     '''
     mpiwem_poynting adj=n aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=600 oz=0 dz=10
     npx=1 dpx=1 opx=0
     nt=1000 dt=0.004 ot=0 
     nsx=1 dsx=100 osx=5000
     gz=10 sz=10
     fmin=1 fmax=40
     ''',np=1,stdin=0,stdout=-1)
Flow('d_fwd_5000wd','d_fwd_5000 wd','math x=${SOURCES[0]} y=${SOURCES[1]} output="x*y"',stdin=0)
Flow('m_adj_5000','d_fwd_5000wd vel wav',
     '''
     mpiwem_poynting adj=y aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=1201 oz=0 dz=7.62
     npx=1 dpx=1 opx=0
     nt=1000 dt=0.004 ot=0 
     nsx=1 dsx=100 osx=5000
     gz=10 sz=10
     fmin=1 fmax=40
     ''',np=1,stdin=0,stdout=-1)
Flow('m_env_5000','m','envelope')
Flow('m_adj_env_5000','m_adj_5000','envelope')
Flow('illum_5000','m_env_5000 m_adj_env_5000','math x=${SOURCES[1]} output="input/(x+0.01)"')

Flow('d_fwd_10000','m vel wav',
     '''
     mpiwem_poynting adj=n aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=600 oz=0 dz=10
     npx=1 dpx=1 opx=0
     nt=1000 dt=0.004 ot=0 
     nsx=1 dsx=100 osx=10000
     gz=10 sz=10
     fmin=1 fmax=40
     ''',np=1,stdin=0,stdout=-1)
Flow('d_fwd_10000wd','d_fwd_10000 wd','math x=${SOURCES[0]} y=${SOURCES[1]} output="x*y"',stdin=0)
Flow('m_adj_10000','d_fwd_10000wd vel wav',
     '''
     mpiwem_poynting adj=y aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=1201 oz=0 dz=7.62
     npx=1 dpx=1 opx=0
     nt=1000 dt=0.004 ot=0 
     nsx=1 dsx=100 osx=10000
     gz=10 sz=10
     fmin=1 fmax=40
     ''',np=1,stdin=0,stdout=-1)
Flow('m_env_10000','m','envelope')
Flow('m_adj_env_10000','m_adj_10000','envelope')
Flow('illum_10000','m_env_10000 m_adj_env_10000','math x=${SOURCES[1]} output="input/(x+0.01)"')

Flow('d_fwd_15000','m vel wav',
     '''
     mpiwem_poynting adj=n aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=600 oz=0 dz=10
     npx=1 dpx=1 opx=0
     nt=1000 dt=0.004 ot=0 
     nsx=1 dsx=100 osx=15000
     gz=10 sz=10
     fmin=1 fmax=40
     ''',np=1,stdin=0,stdout=-1)
Flow('d_fwd_15000wd','d_fwd_15000 wd','math x=${SOURCES[0]} y=${SOURCES[1]} output="x*y"',stdin=0)
Flow('m_adj_15000','d_fwd_15000wd vel wav',
     '''
     mpiwem_poynting adj=y aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=1201 oz=0 dz=7.62
     npx=1 dpx=1 opx=0
     nt=1000 dt=0.004 ot=0 
     nsx=1 dsx=100 osx=15000
     gz=10 sz=10
     fmin=1 fmax=40
     ''',np=1,stdin=0,stdout=-1)
Flow('m_env_15000','m','envelope')
Flow('m_adj_env_15000','m_adj_15000','envelope')
Flow('illum_15000','m_env_15000 m_adj_env_15000','math x=${SOURCES[1]} output="input/(x+0.01)"')

Flow('d_fwd_20000','m vel wav',
     '''
     mpiwem_poynting adj=n aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=600 oz=0 dz=10
     npx=1 dpx=1 opx=0
     nt=1000 dt=0.004 ot=0 
     nsx=1 dsx=100 osx=20000
     gz=10 sz=10
     fmin=1 fmax=40
     ''',np=1,stdin=0,stdout=-1)
Flow('d_fwd_20000wd','d_fwd_20000 wd','math x=${SOURCES[0]} y=${SOURCES[1]} output="x*y"',stdin=0)
Flow('m_adj_20000','d_fwd_20000wd vel wav',
     '''
     mpiwem_poynting adj=y aa=n
     infile=${SOURCES[0]} vp=${SOURCES[1]} wav=${SOURCES[2]} 
     outfile=${TARGETS[0]}
     verbose=y
     nz=1201 oz=0 dz=7.62
     npx=1 dpx=1 opx=0
     nt=1000 dt=0.004 ot=0 
     nsx=1 dsx=100 osx=20000
     gz=10 sz=10
     fmin=1 fmax=40
     ''',np=1,stdin=0,stdout=-1)
Flow('m_env_20000','m','envelope')
Flow('m_adj_env_20000','m_adj_20000','envelope')
Flow('illum_20000','m_env_20000 m_adj_env_20000','math x=${SOURCES[1]} output="input/(x+0.01)"')

Result('vel','grey color=j allpos=y mean=2000 title="" label2=X unit2=m')
Result('m','put o2=3055.62 | grey color=i minval=-0.5 maxval=0.5 clip=0.5 title="" label1=Z unit1=m label2=X unit2=m')
Result('illum_5000','put o2=3055.62 | grey color=j allpos=y minval=0 maxval=10 clip=10 title="" label1=Z unit1=m label2=X unit2=m polarity=y')
Result('illum_10000','put o2=3055.62 | grey color=j allpos=y minval=0 maxval=10 clip=10 title="" label1=Z unit1=m label2=X unit2=m polarity=y')
Result('illum_15000','put o2=3055.62 | grey color=j allpos=y minval=0 maxval=10 clip=10 title="" label1=Z unit1=m label2=X unit2=m polarity=y')
Result('illum_20000','put o2=3055.62 | grey color=j allpos=y minval=0 maxval=10 clip=10 title="" label1=Z unit1=m label2=X unit2=m polarity=y')

End()


