from rsf.tex import *

Paper('slides',
     lclass='cwpslides',
     use='multicol,color,overpic,listings,amsmath,amssymb,amsbsy,comment,textpos,epstopdf,epsfig,algorithm,algpseudocode',
     color='ALL')

End(use='color')
